# Generated by Django 4.1.6 on 2023-02-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_modelyangi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modelyangi',
        ),
    ]
