# Generated by Django 4.1.6 on 2023-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_newmodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbase',
            name='image',
            field=models.ImageField(default='', upload_to='firstapp/images'),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2),
        ),
    ]
