# Generated by Django 4.1.6 on 2023-02-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_newsbase_image_alter_newsbase_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsbase',
            old_name='bodys',
            new_name='body',
        ),
    ]
