# Generated by Django 4.1.6 on 2023-02-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_rename_bodys_newsbase_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbase',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsbase',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
