# Generated by Django 4.1.6 on 2023-03-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_rename_name_alluser_first_name_alter_newsbase_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbase',
            name='slug',
            field=models.SlugField(),
        ),
    ]
