# Generated by Django 4.1.6 on 2023-03-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='status',
            new_name='active',
        ),
    ]
