# Generated by Django 4.1.6 on 2023-03-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_rename_status_comments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsbase',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
