# Generated by Django 4.1.7 on 2023-03-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_remove_newsbase_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsbase',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
