# Generated by Django 4.1.7 on 2023-03-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_newsbase_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsbase',
            options={'ordering': ['-publish_time', 'view_count']},
        ),
    ]
